// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finalWS_2015233.Data;

namespace finalWS_2015233.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("finalWS_2015233.Models.Client", b =>
                {
                    b.Property<int>("Client_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("First_name")
                        .HasColumnType("longtext");

                    b.Property<string>("Last_name")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone_number")
                        .HasColumnType("longtext");

                    b.HasKey("Client_Id");

                    b.ToTable("client");
                });

            modelBuilder.Entity("finalWS_2015233.Models.ProjectToClient", b =>
                {
                    b.Property<int>("Connection_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Client_Id")
                        .HasColumnType("int");

                    b.Property<int?>("SolarisPrjProject_Id")
                        .HasColumnType("int");

                    b.HasKey("Connection_Id");

                    b.HasIndex("Client_Id");

                    b.HasIndex("SolarisPrjProject_Id");

                    b.ToTable("prj_to_client");
                });

            modelBuilder.Entity("finalWS_2015233.Models.SolarisPrj", b =>
                {
                    b.Property<int>("Project_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<DateTime>("Due_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Project_Title")
                        .HasColumnType("longtext");

                    b.HasKey("Project_Id");

                    b.ToTable("solaris_project");
                });

            modelBuilder.Entity("finalWS_2015233.Models.ProjectToClient", b =>
                {
                    b.HasOne("finalWS_2015233.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Client_Id");

                    b.HasOne("finalWS_2015233.Models.SolarisPrj", "SolarisPrj")
                        .WithMany()
                        .HasForeignKey("SolarisPrjProject_Id");

                    b.Navigation("Client");

                    b.Navigation("SolarisPrj");
                });
#pragma warning restore 612, 618
        }
    }
}
